---
- name: Install dependencies for apt_* modules
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ apt_dependencies }}"
    state: present

- name: Install Debian distribution specific base packages
  ansible.builtin.apt:
    name: '{{ distro_packages }}'
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install qemu-guest-agent if KVM VM
  ansible.builtin.apt:
    name: qemu-guest-agent
  when: ansible_facts['virtualization_role'] == 'guest' and ansible_facts['virtualization_type'] == 'kvm'

- name: Ensure qemu-guest-agent is running if KVM VM
  ansible.builtin.systemd:
    name: 'qemu-guest-agent'
    state: started
    enabled: yes
    daemon_reload: yes
  when: ansible_facts['virtualization_role'] == 'guest' and ansible_facts['virtualization_type'] == 'kvm'

- name: Ensure /etc/default/grub
  ansible.builtin.template:
    src: templates/etc/default/grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  notify: update-grub

- name: Ensure ubuntu specific files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /root/.zshrc
    - /etc/skel/.zshrc
    - /etc/logrotate.conf
    - /etc/default/useradd

